root: /
baseurl: http://du.zoomquiet.io
permalink: /:year-:month/:title/
markdown: kramdown

markdown_ext:  markdown,md

paginate: 3
paginate_path: '/page:num'

gems:
  - jekyll-archives
  - jekyll-paginate

title: 自怼圈
email: "zoomquiet+du@gmail.com"
authors: 
    du:
        name: DebugUself
        display_name: DU
        gravatar: 3afb962feeb8c047cde19b19ba62e27a
        email: debuguself@googlegroups.com
        web: https://github.com/DebugUself
        github: DebugUself
        gittip: https://www.gittip.com/ZoomQuiet/
    zq:
        name: Zoom Quiet
        display_name: Zoom.Quiet
        gravatar: a50dc106c1d703b0c5b46be577ddd527
        email: i@zoomquiet.io
        web: http://zoomquiet.io
        github: ZoomQuiet
        gittip: https://www.gittip.com/ZoomQuiet/
    zoe:
        name: Zoe Jane
        display_name: Zoe Jane
        gravatar: 20923f7c8894084554282df11e745e80
        email: dadac123@gmail.com
        web: http://zoejane.net
        github: zoejane
        gittip: https://www.gittip.com/
    sunoonlee:
        name: sunoonlee
        display_name: sunoonlee
        gravatar: 998b9328ec80486550786ebac4b51a71
        email: helloliming@gmail.com
        web: https://sunoonlee.github.io
        github: sunoonlee
        gittip: https://www.gittip.com/sunoonlee
    xpgeng:
        name: xpgeng
        display_name: xpgeng
        gravatar: 4e8debd173dd76ba7982011ea4b3ffa4
        email: xpgeng.me@gmail.com
        web: http://xpgeng.me/
        github: xpgeng
        gittip: https://www.gittip.com/xpgeng
    bambooom:
        name: bambooom
        display_name: bamboo
        gravatar: fa1b9bd7025779aeb9a53cfff1c371ac
        email: nmz89825@gmail.com
        web: https://bambooom.github.io/
        github: bambooom
        gittip: https://gratipay.com/~bambooom/


exclude:
  - README.md
